// ELEC2645 Multi-Game Menu System Demo
// =====================================
// A collaborative game development framework with a state machine-based menu system.
// 
// KEY CONCEPTS:
// - State Machine: Menu system manages navigation between main menu and 3 games
// - Event-Driven Architecture: BT2/BT3 buttons use interrupt callback for fast response
// - Debouncing: Software debouncing to handle button noise
// - Modular Design: Each game (game_1, game_2, game_3) is independent with own loop
// - Shared Resources: Common utilities and LCD in shared/ folder
// - Flexible Frame Rates: Each game controls its own update/render speed
//
// Controls:
// - BT2/BT3 (Buttons): Available for game use
// - Joystick UP/DOWN: Menu navigation and game input
//
// Architecture:
// - MenuSystem: Runs its own loop, returns selected game
// - Game modules: Each has Game_Run() with own loop, returns next state
// - Shared utilities: LCD, Joystick, etc. in shared/ folder


// STM32 HAL headers (auto-generated by STM32CubeMX)
#include "main.h"
#include "tim.h"       // Timer 2 for PWM buzzer control
#include "usart.h"     // For serial output
#include "gpio.h"      // GPIO control
#include "adc.h"       // ADC for joystick input
#include "rng.h"       // RNG for randomized ball reset

// AUTO-GENERATED STM32 FUNCTION PROTOTYPES - DO NOT EDIT
void SystemClock_Config(void);
void PeriphCommonClock_Config(void);

// HAL Drivers and Utilities
#include "Buzzer.h"    // Buzzer control via PWM
#include "PWM.h"       // PWM control for LED 
#include "LCD.h"       // LCD display driver
#include "Joystick.h"  // Joystick input
#include "Utils.h"     // Common utility types

// Menu System and Input
#include "Menu.h"      // Menu state machine and UI
#include "InputHandler.h" // Input reading

#include <stdint.h>
#include <stdio.h>
#include <math.h>

// ===== FORWARD DECLARATIONS FOR GAMES =====
// Each game implements a Run function that returns the next state
MenuState Game1_Run(void);
MenuState Game2_Run(void);
MenuState Game3_Run(void);

// ===== BUZZER CONFIGURATION =====
// Configure buzzer to use TIM2 Channel 3 (current hardware setup)
Buzzer_cfg_t buzzer_cfg = {
    .htim = &htim2,
    .channel = TIM_CHANNEL_3,
    .tick_freq_hz = 1000000,  // 1MHz timer clock (prescaler = 79 with 80MHz input)
    .min_freq_hz = 20,
    .max_freq_hz = 20000,
    .setup_done = 0
};

// ===== LCD CONFIGURATION =====
ST7789V2_cfg_t cfg0 = {
    .setup_done = 0,
    .spi = SPI2,
    .RST = {.port = GPIOB, .pin = GPIO_PIN_2},
    .BL = {.port = GPIOB, .pin = GPIO_PIN_1},
    .DC = {.port = GPIOB, .pin = GPIO_PIN_11},
    .CS = {.port = GPIOB, .pin = GPIO_PIN_12},
    .MOSI = {.port = GPIOB, .pin = GPIO_PIN_15},
    .SCLK = {.port = GPIOB, .pin = GPIO_PIN_13},
    .dma = {.instance = DMA1, .channel = DMA1_Channel5}
};

// ===== JOYSTICK CONFIGURATION =====
Joystick_cfg_t joystick_cfg = {
    .adc = &hadc1,
    .x_channel = ADC_CHANNEL_1, //A5 on Nucleo board
    .y_channel = ADC_CHANNEL_2, //A4 on Nucleo board
    .sampling_time = ADC_SAMPLETIME_47CYCLES_5,
    .center_x = JOYSTICK_DEFAULT_CENTER_X,
    .center_y = JOYSTICK_DEFAULT_CENTER_Y,
    .deadzone = JOYSTICK_DEADZONE,
    .setup_done = 0
};

// Joystick data structure to hold readings
Joystick_t joystick_data;

// ===== PWM CONFIGURATION =====
// Configure PWM to use TIM4 Channel 1 (current hardware setup)
PWM_cfg_t pwm_cfg = {
    .htim = &htim4,
    .channel = TIM_CHANNEL_1,
    .tick_freq_hz = 1000000,  // 1MHz timer clock (prescaler = 79 with 80MHz input)
    .min_freq_hz = 10,
    .max_freq_hz = 50000,
    .setup_done = 0
};

// ===== MENU SYSTEM STATE =====
MenuSystem menu;

// ===== TIMER TICK COUNTERS =====
// These remain active while TIM6/TIM7 interrupts are running.
volatile uint32_t g_tim6_ticks = 0;
volatile uint32_t g_tim7_ticks = 0;

// ===== BUTTON DEBOUNCING CONFIGURATION =====
#define DEBOUNCE_DELAY 200  // 200ms debounce time

// ===== TIMER CONFIGURATION =====
// Available timers for student use:
//
// TIM2: PWM for Buzzer (1MHz tick, used by buzzer_cfg)
// TIM4: PWM for LED control (1MHz tick, used by pwm_cfg)
// TIM6: General purpose timer with interrupt (100Hz / 10ms period)
//       - ISR processing is centralized in HAL_TIM_PeriodElapsedCallback(...)
//       - Incrementing g_tim6_ticks every 10 ms while active
// TIM7: General purpose timer with interrupt (1Hz / 1s period)
//       - Configured for 1s interrupts (1 Hz)
//       - Optional second scheduler (left commented in main init)
//       - Incrementing g_tim7_ticks every 1 s while active
//
// Note: Both TIM6 and TIM7 are initialized but NOT started.
//       Students should start them in their game with HAL_TIM_Base_Start_IT()
//       and stop them with HAL_TIM_Base_Stop_IT() when returning to menu.


// ===== UTILITY FUNCTIONS =====

/**
 * @brief Redirect printf to UART for debugging
 */
int _write(int file, char *ptr, int len) {
    HAL_UART_Transmit(&huart2, (uint8_t*)ptr, len, HAL_MAX_DELAY);
    return len;
}

// ===== EXTERNAL INTERRUPT HANDLER FOR BT3 (Joystick Button) =====
/**
 * @brief HAL callback for external interrupts (button presses)
 * 
 * This simply sets a flag that the main loop will check once per frame
 * in InputHandler_Read(). This provides debouncing and clean separation
 * between interrupt handling and main game logic.
 * 
 * Based on Unit_3_4_Event_Trigger pattern.
 */
void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin);  // Implemented in InputHandler.c

/**
 * @brief HAL callback for timer period elapsed interrupts
 *
 * TIM6/TIM7 periodic interrupts are handled centrally here.
 */
void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim)
{
  if (htim->Instance == TIM6) {
    g_tim6_ticks++;
  }
  else if (htim->Instance == TIM7) {
    g_tim7_ticks++;
  }
}


// ===== Main Function =====
/**
  * @brief  The application entry point - Menu System with Simple Game Loop
  * @retval int
  */
int main(void)
{
    /* MCU Configuration */
    HAL_Init();
    SystemClock_Config();
    PeriphCommonClock_Config();

    /* Initialize peripherals */
    MX_GPIO_Init();
    MX_USART2_UART_Init();
    MX_ADC1_Init();  // Initialize ADC for joystick
    MX_RNG_Init();   // Initialize RNG (if used by games)
    
    // Initialize LCD first (this sets up GPIOB pins)
    LCD_init(&cfg0);

    // Initialize buzzer timer
    MX_TIM2_Init();
    buzzer_init(&buzzer_cfg);

    // Initialize TIM4 AFTER LCD to avoid GPIO conflict on PB6
    MX_TIM4_Init();
    
    // Initialize general-purpose timers (available for student use)
    // TIM6: 100ms interrupt timer (10 Hz) - Prescaler=7999, Period=99
    //       Tick frequency = 80MHz / (7999+1) / (99+1) = 100Hz (10ms period)
    // TIM7: 1000ms interrupt timer (1 Hz) - Prescaler=7999, Period=9999
    //       Tick frequency = 80MHz / (7999+1) / (9999+1) = 1Hz (1s period)
    MX_TIM6_Init();
    MX_TIM7_Init();

    // Start TIM6 interrupt so a 10ms periodic tick is always available.
    HAL_TIM_Base_Start_IT(&htim6);

    // TIM7 is available if students want a second slower periodic trigger.
    // HAL_TIM_Base_Start_IT(&htim7);
  
    // Initialize Input System (button handling)
    Input_Init();
    
    // Initialize Joystick
    Joystick_Init(&joystick_cfg);
    
    // Clear screen
    LCD_Fill_Buffer(0);
    LCD_Refresh(&cfg0);

    // Startup animation
    LCD_printString("MENU SYSTEM", 40, 50, 1, 2);
    LCD_printString("Starting...", 50, 100, 1, 2);
    LCD_Refresh(&cfg0);
    HAL_Delay(1000);
    
    // Initialize PWM for LED control
    PWM_Init(&pwm_cfg);
    PWM_SetFreq(&pwm_cfg, 1000);
    PWM_SetDuty(&pwm_cfg, 50);  // Start at 50% brightness
    
    // Ensure LD2 on PA5 starts OFF
    HAL_GPIO_WritePin(GPIOA, GPIO_PIN_5, GPIO_PIN_RESET);

    // ===== INITIALIZE MENU SYSTEM =====
    Menu_Init(&menu);
    
    printf("Menu system initialized. Press BT3 to select.\n");

    // ===== MAIN GAME LOOP =====
    // Hybrid pattern: Each component (menu/games) runs its own loop
    // and returns the next state when done
    MenuState current_state = MENU_STATE_HOME;
    
    while (1)
    {
        switch (current_state) {
            case MENU_STATE_HOME:
                // Run menu - returns selected game
                current_state = Menu_Run(&menu);
                break;
                
            case MENU_STATE_GAME_1:
                // Run Game 1 - returns next state when done
                current_state = Game1_Run();
                break;
                
            case MENU_STATE_GAME_2:
                // Run Game 2 - returns next state when done
                current_state = Game2_Run();
                break;
                
            case MENU_STATE_GAME_3:
                // Run Game 3 - returns next state when done
                current_state = Game3_Run();
                break;
                
            default:
                // Unknown state - return to menu
                current_state = MENU_STATE_HOME;
                break;
        }
    }
    
    return 0;
}


// ===== GAME IMPLEMENTATION =====
// Games are implemented in:
//   - game_1/Game_1.c
//   - game_2/Game_2.c  
//   - game_3/Game_3.c
//
// Each student implements their own game in their folder while sharing
// common utilities from the shared/ folder and LCD via the Menu system.





// ==== AUTO-GENERATED STM32 FUNCTIONS ====
// DO NOT EDIT UNLESS YOU KNOW WHAT YOU ARE DOING! 


/**
  * @brief System Clock Configuration
  * @retval None
  */
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  /** Configure the main internal regulator output voltage
  */
  if (HAL_PWREx_ControlVoltageScaling(PWR_REGULATOR_VOLTAGE_SCALE1) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
  RCC_OscInitStruct.HSIState = RCC_HSI_ON;
  RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI;
  RCC_OscInitStruct.PLL.PLLM = 1;
  RCC_OscInitStruct.PLL.PLLN = 10;
  RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV7;
  RCC_OscInitStruct.PLL.PLLQ = RCC_PLLQ_DIV2;
  RCC_OscInitStruct.PLL.PLLR = RCC_PLLR_DIV2;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_4) != HAL_OK)
  {
    Error_Handler();
  }
}

/**
  * @brief Peripherals Common Clock Configuration
  * @retval None
  */
void PeriphCommonClock_Config(void)
{
  RCC_PeriphCLKInitTypeDef PeriphClkInit = {0};

  /** Initializes the peripherals clock
  */
  PeriphClkInit.PeriphClockSelection = RCC_PERIPHCLK_RNG|RCC_PERIPHCLK_ADC;
  PeriphClkInit.AdcClockSelection = RCC_ADCCLKSOURCE_PLLSAI1;
  PeriphClkInit.RngClockSelection = RCC_RNGCLKSOURCE_PLLSAI1;
  PeriphClkInit.PLLSAI1.PLLSAI1Source = RCC_PLLSOURCE_HSI;
  PeriphClkInit.PLLSAI1.PLLSAI1M = 1;
  PeriphClkInit.PLLSAI1.PLLSAI1N = 8;
  PeriphClkInit.PLLSAI1.PLLSAI1P = RCC_PLLP_DIV7;
  PeriphClkInit.PLLSAI1.PLLSAI1Q = RCC_PLLQ_DIV4;
  PeriphClkInit.PLLSAI1.PLLSAI1R = RCC_PLLR_DIV2;
  PeriphClkInit.PLLSAI1.PLLSAI1ClockOut = RCC_PLLSAI1_48M2CLK|RCC_PLLSAI1_ADC1CLK;
  if (HAL_RCCEx_PeriphCLKConfig(&PeriphClkInit) != HAL_OK)
  {
    Error_Handler();
  }
}



/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
  /* USER CODE BEGIN Error_Handler_Debug */
  /* User can add his own implementation to report the HAL error return state */
  __disable_irq();
  while (1)
  {
  }
  /* USER CODE END Error_Handler_Debug */
}
#ifdef USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file and the source line number
  *         where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t *file, uint32_t line)
{
  /* USER CODE BEGIN 6 */
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */
  /* USER CODE END 6 */
}
#endif /* USE_FULL_ASSERT */
